name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Your first issue! Thank you for contributing to the project, I think we are going to build create things together."
          pr-message: "A pull request? You must have been up to big things, thank you for contributing to the project. Let's create something great together."
